version: '3.1'

services:

  mongo:
    image: mongo:4.4.17
    restart: always
    container_name: 'mongo'
    hostname: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
