# Generated by Django 4.1.1 on 2022-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_review_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='name_country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
