# Generated by Django 4.1.1 on 2022-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_places_name_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pending_users',
        ),
        migrations.AddField(
            model_name='event',
            name='event_users',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='name_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='stopping_point',
            field=models.CharField(max_length=50),
        ),
    ]
