# Generated by Django 4.1.1 on 2022-11-08 19:27

from django.db import migrations, models
from utils import validators


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_remove_event_approved_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(validators=[validators.validate_event_price]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(validators=[validators.validate_event_date]),
        ),
    ]
